/* __imports_rewritten__ */
import React from 'https://esm.sh/react@19.2.0';
import { html } from '../jsx.js';
import { Link, useNavigate, useParams } from 'https://esm.sh/react-router-dom@7.13.0?deps=react@19.2.0';
import {Plus, Save, Trash2, ArrowLeft} from 'https://esm.sh/lucide-react?deps=react@19.2.0';
import { useBillingStore } from '../store/useBillingStore.js';
import { money, invoiceTotals, today, invoiceLineTaxRate, invoiceLineTotal, invoiceTaxBreakup, invoiceLineTaxValue } from '../utils/format.js';

const paymentModes = ['Cash', 'UPI', 'GPay', 'PhonePe', 'Paytm', 'Card', 'Bank Transfer', 'NEFT / RTGS', 'Cheque', 'Credit', 'Other'];

export function InvoiceEditor() {
  const navigate = useNavigate();
  const params = useParams();
  const editId = params.id || '';
  const customers = useBillingStore(s => s.customers);
  const items = useBillingStore(s => s.items);
  const invoices = useBillingStore(s => s.invoices);
  const settings = useBillingStore(s => s.settings);
  const addInvoice = useBillingStore(s => s.addInvoice);
  const updateInvoice = useBillingStore(s => s.updateInvoice);
  const nextInvoiceNumber = useBillingStore(s => s.nextInvoiceNumber);
  const existingInvoice = editId ? invoices.find(inv => inv.id === editId) : null;
  const makeBlankInvoice = () => ({ number: nextInvoiceNumber(), date: today(), dueDate: today(), customerId: customers[0]?.id || '', status: 'Unpaid', paymentMode: 'Cash', customPaymentMode: '', notes: '', discount: '', discountType: 'amount', taxMode: 'GST', cgstRate: Number(settings.defaultCgstRate ?? 9), sgstRate: Number(settings.defaultSgstRate ?? 9), paid: '', items: [] });
  const normalizePaymentFields = inv => paymentModes.includes(inv.paymentMode || '') ? { paymentMode: inv.paymentMode || 'Cash', customPaymentMode: inv.customPaymentMode || '' } : { paymentMode: 'Other', customPaymentMode: inv.paymentMode || inv.customPaymentMode || '' };
  const [invoice, setInvoice] = React.useState(() => existingInvoice ? { ...makeBlankInvoice(), ...existingInvoice, ...normalizePaymentFields(existingInvoice), taxMode: existingInvoice.taxMode === 'CUSTOM' ? 'GST' : (existingInvoice.taxMode || 'GST'), cgstRate: Number(existingInvoice.cgstRate ?? settings.defaultCgstRate ?? 9), sgstRate: Number(existingInvoice.sgstRate ?? settings.defaultSgstRate ?? 9), items: existingInvoice.items || [] } : makeBlankInvoice());
  const [notFound, setNotFound] = React.useState('');
  const availableItems = items.filter(i => !i.partyId || i.partyId === invoice.customerId);
  const totals = invoiceTotals(invoice);
  const taxBreakup = invoiceTaxBreakup(invoice);
  const gstRate = Number(invoice.cgstRate || 0) + Number(invoice.sgstRate || 0);
  const displayPaymentMode = invoice.paymentMode === 'Other' ? (invoice.customPaymentMode || 'Other') : (invoice.paymentMode || 'Cash');
  const numberOrBlank = value => value === '' ? '' : Number(value);
  const displayBlankZero = value => Number(value || 0) === 0 ? '' : value;

  React.useEffect(() => {
    if (!editId) return;
    const found = invoices.find(inv => inv.id === editId);
    if (found) setInvoice({ ...makeBlankInvoice(), ...found, ...normalizePaymentFields(found), taxMode: found.taxMode === 'CUSTOM' ? 'GST' : (found.taxMode || 'GST'), cgstRate: Number(found.cgstRate ?? settings.defaultCgstRate ?? 9), sgstRate: Number(found.sgstRate ?? settings.defaultSgstRate ?? 9), items: found.items || [] });
  }, [editId]);

  if (editId && !existingInvoice) return html`<div className="card p-8"><p className="font-black">Invoice not found for edit.</p><${Link} to="/invoices" className="mt-4 inline-flex items-center gap-2 text-[hsl(var(--primary))]"><${ArrowLeft} size=${16} /> Back to invoices</${Link}></div>`;

  const addLine = () => {
    const it = availableItems[0] || items[0];
    setInvoice(v => ({ ...v, items: [...v.items, it ? { itemId: it.id, name: it.name, qty: 1, price: it.salePrice, taxRate: it.taxRate, hsn: it.hsn, discount: '', discountType: 'amount' } : { itemId: '', name: '', qty: '', price: '', taxRate: '', hsn: '', discount: '', discountType: 'amount' }] }));
  };
  const updateLine = (index, patch) => setInvoice(v => ({ ...v, items: v.items.map((line, i) => i === index ? { ...line, ...patch } : line) }));
  const chooseItem = (index, id) => { const it = items.find(x => x.id === id); setNotFound(''); if (it) updateLine(index, { itemId: it.id, name: it.name, price: it.salePrice, taxRate: it.taxRate, hsn: it.hsn }); else updateLine(index, { itemId: '' }); };
  const changeName = (index, value) => { const found = availableItems.find(i => String(i.name || '').trim().toLowerCase() === String(value || '').trim().toLowerCase()); setNotFound(value.trim() && !found ? 'Product not found in products list.' : ''); updateLine(index, found ? { itemId: found.id, name: found.name, price: found.salePrice, taxRate: found.taxRate, hsn: found.hsn } : { name: value, itemId: '' }); };
  const removeLine = index => setInvoice(v => ({ ...v, items: v.items.filter((_, i) => i !== index) }));
  const save = () => { if (invoice.items.length === 0) { addLine(); return; } if (invoice.items.some(line => !String(line.name || '').trim())) return alert('Please select a product or type item name.'); if (invoice.paymentMode === 'Other' && !String(invoice.customPaymentMode || '').trim()) return alert('Please enter custom payment mode.'); const finalPaymentMode = invoice.paymentMode === 'Other' ? String(invoice.customPaymentMode || '').trim() : (invoice.paymentMode || 'Cash'); const status = finalPaymentMode === 'Credit' ? (Number(invoice.paid || 0) >= totals.total ? 'Paid' : Number(invoice.paid || 0) > 0 ? 'Partial' : invoice.status) : 'Paid'; const paid = finalPaymentMode === 'Credit' ? Number(invoice.paid || 0) : totals.total; const saved = { ...invoice, paid, paymentMode: finalPaymentMode, customPaymentMode: invoice.paymentMode === 'Other' ? finalPaymentMode : '', taxMode: invoice.taxMode === 'CUSTOM' ? 'GST' : invoice.taxMode, status }; editId ? updateInvoice(editId, saved) : addInvoice(saved); navigate('/invoices'); };

  return html`
    <div className="space-y-5">
      ${editId ? html`<div className="flex flex-wrap items-center justify-between gap-3"><${Link} to=${`/invoices/${editId}`} className="inline-flex items-center gap-2 rounded-[var(--radius-md)] border border-[hsl(var(--border))] px-4 py-2 font-bold"><${ArrowLeft} size=${17} /> Back</${Link}><p className="rounded-full bg-[hsl(var(--primary)/0.12)] px-4 py-2 text-sm font-black text-[hsl(var(--primary))]">Editing: ${invoice.number}</p></div>` : ''}
      <div className="card p-5">
        <div className="grid gap-4 md:grid-cols-6">
          <label className="text-sm font-bold">Invoice No<input value=${invoice.number} onInput=${e => setInvoice({ ...invoice, number: e.target.value })} className="focus-ring mt-1 w-full rounded-[var(--radius-md)] border border-[hsl(var(--border))] bg-transparent p-3" /></label>
          <label className="text-sm font-bold">Customer<select value=${invoice.customerId} onChange=${e => setInvoice({ ...invoice, customerId: e.target.value, items: [] })} className="focus-ring mt-1 w-full rounded-[var(--radius-md)] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-3">${customers.map(c => html`<option key=${c.id} value=${c.id}>${c.name}</option>`)}</select></label>
          <label className="text-sm font-bold uppercase tracking-wide text-[hsl(var(--muted-foreground))]">Payment Mode<select value=${invoice.paymentMode || 'Cash'} onChange=${e => setInvoice({ ...invoice, paymentMode: e.target.value, status: e.target.value === 'Credit' ? invoice.status : 'Paid' })} className="focus-ring mt-1 w-full rounded-[var(--radius-md)] border border-[hsl(var(--primary))] bg-[hsl(var(--card))] p-3 text-base font-normal normal-case tracking-normal text-[hsl(var(--foreground))] shadow-[0_0_0_2px_hsl(var(--primary)/0.10)]">${paymentModes.map(mode => html`<option key=${mode} value=${mode}>${mode}</option>`)}</select></label>
          <label className="text-sm font-bold">Tax Type<select value=${invoice.taxMode === 'CUSTOM' ? 'GST' : invoice.taxMode} onChange=${e => setInvoice({ ...invoice, taxMode: e.target.value })} className="focus-ring mt-1 w-full rounded-[var(--radius-md)] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-3"><option value="GST">GST</option><option value="IGST">IGST</option></select></label>
          <label className="text-sm font-bold">Bill Date<input type="date" value=${invoice.date} onInput=${e => setInvoice({ ...invoice, date: e.target.value })} className="focus-ring mt-1 w-full rounded-[var(--radius-md)] border border-[hsl(var(--border))] bg-transparent p-3" /></label>
          <label className="text-sm font-bold">Due Date<input type="date" value=${invoice.dueDate} onInput=${e => setInvoice({ ...invoice, dueDate: e.target.value })} className="focus-ring mt-1 w-full rounded-[var(--radius-md)] border border-[hsl(var(--border))] bg-transparent p-3" /></label>
        </div>
        ${invoice.paymentMode === 'Other' ? html`<label className="mt-4 block text-sm font-bold">Custom Payment Mode<input value=${invoice.customPaymentMode || ''} onInput=${e => setInvoice({ ...invoice, customPaymentMode: e.target.value })} placeholder="Example: Amazon Pay / Finance / Split Payment" className="focus-ring mt-1 w-full rounded-[var(--radius-md)] border border-[hsl(var(--primary))] bg-transparent p-3" /></label>` : ''}
        ${(invoice.taxMode === 'GST' || invoice.taxMode === 'CUSTOM') ? html`<div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">CGST %<input type="number" value=${invoice.cgstRate} onInput=${e => setInvoice({ ...invoice, cgstRate: numberOrBlank(e.target.value) })} placeholder="CGST %" className="focus-ring mt-1 w-full rounded-[var(--radius-md)] border border-[hsl(var(--border))] bg-transparent p-3" /></label><label className="text-sm font-bold">SGST %<input type="number" value=${invoice.sgstRate} onInput=${e => setInvoice({ ...invoice, sgstRate: numberOrBlank(e.target.value) })} placeholder="SGST %" className="focus-ring mt-1 w-full rounded-[var(--radius-md)] border border-[hsl(var(--border))] bg-transparent p-3" /></label></div>` : ''}
      </div>
      <div className="card overflow-hidden">
        <div className="flex items-center justify-between border-b border-[hsl(var(--border))] p-4"><div><h3 className="font-black">Items</h3>${notFound ? html`<p className="mt-1 text-xs font-bold text-red-600">${notFound}</p>` : ''}</div><button onClick=${addLine} className="inline-flex items-center gap-2 rounded-[var(--radius-md)] bg-[hsl(var(--primary))] px-3 py-2 text-sm font-black text-white"><${Plus} size=${16} /> Add Item</button></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-sm"><thead className="bg-[hsl(var(--muted))] text-left text-xs uppercase text-[hsl(var(--muted-foreground))]"><tr><th className="p-3">Product Dropdown</th><th className="p-3">Product Name</th><th className="p-3">HSN</th><th className="p-3">Qty</th><th className="p-3">Rate</th><th className="p-3">Tax</th><th className="p-3">Discount</th><th className="p-3 text-right">Amount</th><th className="p-3"></th></tr></thead><tbody>
          ${invoice.items.map((line, index) => html`<tr key=${`${line.itemId || 'custom'}-${index}`} className="border-t border-[hsl(var(--border))]"><td className="p-3"><select value=${line.itemId || ''} onChange=${e => chooseItem(index, e.target.value)} className="w-44 rounded-[var(--radius-sm)] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-2"><option value="">${String(line.name || '').trim() || 'Select Product'}</option>${availableItems.map(i => html`<option key=${i.id} value=${i.id}>${i.name}</option>`)}</select></td><td className="p-3"><input value=${line.name || ''} onInput=${e => changeName(index, e.target.value)} placeholder="Product name" className="w-56 rounded-[var(--radius-sm)] border border-[hsl(var(--border))] bg-transparent p-2" /></td><td className="p-3"><input value=${line.hsn || ''} onInput=${e => updateLine(index, { hsn: e.target.value })} placeholder="HSN" className="w-24 rounded-[var(--radius-sm)] border border-[hsl(var(--border))] bg-transparent p-2" /></td><td className="p-3"><input type="number" value=${displayBlankZero(line.qty)} onInput=${e => updateLine(index, { qty: numberOrBlank(e.target.value) })} placeholder="Qty" className="w-20 rounded-[var(--radius-sm)] border border-[hsl(var(--border))] bg-transparent p-2" /></td><td className="p-3"><input type="number" value=${displayBlankZero(line.price)} onInput=${e => updateLine(index, { price: numberOrBlank(e.target.value) })} placeholder="Rate" className="w-28 rounded-[var(--radius-sm)] border border-[hsl(var(--border))] bg-transparent p-2" /></td><td className="p-3 font-bold">${invoice.taxMode === 'IGST' ? `${invoiceLineTaxRate(invoice, line)}%` : `${gstRate}%`} (${money(invoiceLineTaxValue(invoice, line), settings.currency)})</td><td className="p-3"><div className="flex items-center gap-2"><select value=${line.discountType || 'amount'} onChange=${e => updateLine(index, { discountType: e.target.value })} className="w-24 rounded-[var(--radius-sm)] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-2"><option value="amount">₹</option><option value="percent">%</option></select><input type="number" value=${displayBlankZero(line.discount)} onInput=${e => updateLine(index, { discount: numberOrBlank(e.target.value) })} placeholder="Disc" className="w-24 rounded-[var(--radius-sm)] border border-[hsl(var(--border))] bg-transparent p-2 text-right" /></div></td><td className="p-3 text-right font-black">${money(invoiceLineTotal(invoice, line), settings.currency)}</td><td className="p-3 text-right"><button onClick=${() => removeLine(index)} className="text-[hsl(var(--destructive))]"><${Trash2} size=${16} /></button></td></tr>`)}
        </tbody></table></div>
      </div>
      <div className="grid gap-5 lg:grid-cols-2"><div className="card p-5"><label className="text-sm font-bold">Invoice Notes<textarea value=${invoice.notes} onInput=${e => setInvoice({ ...invoice, notes: e.target.value })} className="focus-ring mt-2 min-h-32 w-full rounded-[var(--radius-md)] border border-[hsl(var(--border))] bg-transparent p-3" placeholder="Payment terms, transport details or delivery instructions"></textarea></label></div><div className="card space-y-3 p-5"><div className="flex justify-between"><span>Subtotal</span><b>${money(totals.subtotal, settings.currency)}</b></div><div className="flex justify-between"><span>Discount</span><b>${money(totals.discount, settings.currency)}</b></div><div className="flex justify-between"><span>Taxable Value</span><b>${money(totals.taxable, settings.currency)}</b></div><div className="flex justify-between"><span>Tax</span><b>${invoice.taxMode === 'IGST' ? (invoiceLineTaxRate(invoice, invoice.items[0] || {})) : gstRate}%</b></div><div className="flex justify-between rounded-[var(--radius-sm)] bg-[hsl(var(--muted)/0.55)] px-3 py-2 text-sm"><span>Payment Mode</span><b>${displayPaymentMode}</b></div><label className="flex items-center justify-between gap-4">Paid<input type="number" value=${invoice.paymentMode === 'Credit' ? displayBlankZero(invoice.paid) : totals.total} disabled=${invoice.paymentMode !== 'Credit'} onInput=${e => setInvoice({ ...invoice, paid: numberOrBlank(e.target.value) })} placeholder="Paid amount" className="w-32 rounded-[var(--radius-sm)] border border-[hsl(var(--border))] bg-transparent p-2 text-right disabled:opacity-60" /></label><div className="border-t border-[hsl(var(--border))] pt-3"><div className="flex justify-between text-xl font-black"><span>Total</span><span>${money(totals.total, settings.currency)}</span></div></div><button onClick=${save} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-[var(--radius-md)] bg-[hsl(var(--secondary))] px-5 py-3 font-black text-[hsl(var(--secondary-foreground))]"><${Save} size=${18} /> ${editId ? 'Update Invoice' : 'Save Invoice'}</button></div></div>
    </div>`;
}
